var reasons = [
  "Because your smile can save my entire day.",
  "Because you make the world a little softer.",
  "Because with you, I can finally breathe.",
  "Because your voice sounds like home to me.",
  "Because you understand even my quiet days.",
  "Because I dream about all the adventures and places we will explore together one day.",
  "Because you are brave in your very own way.",
  "Because you know me better than I know myself sometimes.",
  "Because you turn ordinary moments into something special.",
  "Because your sense of humor matches mine completely.",
  "Because you are honest, even when it is uncomfortable.",
  "Because your laughter is so beautiful I can't help but laugh along.",
  "Because even across all the distance, you are more breathtaking than any place in the world.",
  "Because you have dreams and you take them seriously.",
  "Because you treat people with genuine warmth.",
  "Because you notice the little details that others miss.",
  "Because you accept me just the way I am.",
  "Because you can turn chaos into calm.",
  "Because your eyes tell stories.",
  "Because you are strong, yet always remain tender.",
  "Because every late night call with you feels like a dream I never want to wake up from.",
  "Because you inspire me to be a better person.",
  "Because you know when words help and when silence is needed.",
  "Because I can talk to you about anything.",
  "Because you are so beautiful, inside and out.",
  "Because you turn small gestures into grand moments.",
  "Because you believe, even when I doubt.",
  "Because I can't wait for the moment I can finally hold your hand for the very first time.",
  "Because you are curious and eager to explore the world.",
  "Because no matter how many miles separate us, having you in my life makes me feel right at home.",
  "Because you make me dream.",
  "Because you are never afraid to show real emotions.",
  "Because you tell stories I could listen to for hours.",
  "Because you make me think deeply.",
  "Because you never stop growing.",
  "Because you stand up fiercely for the people you love.",
  "Because you give me safety without making me feel confined.",
  "Because you make an ordinary evening feel magical.",
  "Because you are so brilliant and so warm-hearted all at once.",
  "Because you embrace my quirks with humor.",
  "Because you show me what love truly means.",
  "Because you are truly present in every moment.",
  "Because you share your dreams with me.",
  "Because you remind me of what truly matters.",
  "Because you are so beautifully imperfect.",
  "Because you make me smile even when I don't feel like it.",
  "Because you are patient, even with me.",
  "Because you inspire me without even trying.",
  "Because you are my favorite person in the world.",
  "Because you surprise me, again and again.",
  "Because you can express so much feeling in so few words.",
  "Because you truly see me for who I am.",
  "Because you encourage me gently, without pressure.",
  "Because you are wonderfully unique and strong-willed.",
  "Because you turn coincidences into cherished memories.",
  "Because you always know when I need you.",
  "Because you love so deeply without needing to be loud.",
  "Because you make my future brighter.",
  "Because you stand by me even through tough times.",
  "Because you carry so much gentleness within you.",
  "Because you make me feel truly free.",
  "Because you find beauty in the simplest things.",
  "Because you can share and hold my deepest thoughts.",
  "Because your laughter is so genuine.",
  "Because you show me that love can be found in everyday life.",
  "Because you never make fun of dreams.",
  "Because you think with your heart.",
  "Because being with you makes me so proud.",
  "Because you bring so much light wherever you go.",
  "Because you remind me of the person I want to be.",
  "Because the closeness you give feels safe and warm.",
  "Because you can be wonderfully chaotic yet so clear all at once.",
  "Because you make me feel chosen, every single day.",
  "Because you make time for us.",
  "Because you inspire me to grow.",
  "Because you turn silence into peaceful togetherness.",
  "Because you deserve all the love in the world, and even more.",
  "Because you are my favorite conversation.",
  "Because you love me even on my difficult days.",
  "Because you bring hope into my life.",
  "Because you are completely authentic.",
  "Because you show me that tenderness is true strength.",
  "Because you collect memories, not just days.",
  "Because you make me better without trying to change who I am.",
  "Because your sweet messages and calls bring so much warmth to my heart.",
  "Because you bridge dreams and reality together.",
  "Because whenever I see you smiling at me, I know I found my home.",
  "Because you have so much heart.",
  "Because you remind me of all the good things in life.",
  "Because you don't view love as something to be earned.",
  "Because you are so wonderfully intricate and deep.",
  "Because you give me space and closeness at the same time.",
  "Because you make the world so much more colorful.",
  "Because you make me fall in love with you all over again.",
  "Because a single glance from you tells an entire story.",
  "Because you are so precious.",
  "Because you are my favorite reason to wake up in the morning.",
  "Because you taught me what true comfort and belonging feel like.",
  "Because you are simply My babyy Yukie, and that is everything.",
  "Because I love you. Period. And once more: because I love you.",
];
